accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path("sign-up", views.SignUpView.as_view(), name="signup"),
    path('<user_id>', views.user_profile, name='user'),
]

app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
]

imgur/urls.py
from django.contrib import admin
from django.urls import include,path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('images/', include('app.urls')),
    path('', views.index, name='index'), 
]

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models
from django.db.models import constraints
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class TimeStamped(models.Model):
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField(editable=False)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()

        self.updated_at = timezone.now()
        return super(TimeStamped, self).save(*args, **kwargs)

    class Meta:
        abstract = True

app/forms.py
from .models import  Comment
from django import forms
from django.forms import ModelForm, fields
from bootstrap_datepicker_plus.widgets import DateTimePickerInput



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        button = ['approved']

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import generic




# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

def user_profile(request,user_id):
   
    context = {
        
    }
    return render(request, 'app/user.html' ,context)
    

app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse,reverse_lazy

# Create your views here.


def index(request):
    return render(request, 'app/index.html')

app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>Music Tribe</title>

    <link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      crossorigin="anonymous"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      rel="stylesheet"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      crossorigin="anonymous"
      integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      crossorigin="anonymous"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      crossorigin="anonymous"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    ></script>

    {% block extrahead %} {% endblock %}

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}" />
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Music Tribe</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/"
                >Home <span class="sr-only">(current)</span></a
              >
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">Hi {{ user.username }}!</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin Dashboard</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%  url 'accounts:signup' %}">Signup</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">Music Tribe</h1>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">{% block content %} {% endblock %}</div>
      </div>
    </div>
  </body>
</html>

app/templates/app/index.html
{% extends 'app/base.html' %} {% block content %}
<div class="row">
  <div class="col-md-10">
    <p><a href="#">hello</a></p>
  </div>
</div>

{% endblock %}

app/templates/includes/bs4_form.html
{% load widget_tweaks %} 

{% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}
  
    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}
  
    {% for field in form.visible_fields %}
      <div class="row form-group">
          <div class="col-md-8 contorls mx-auto">
            {{ field.label_tag }}
    
            {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
            {% else %}
            {% render_field field class="form-control" %}
            {% endif %}
    
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
      </div>
    {% endfor %}